<div class="hidden">
  <span class="-left-[9px] -ml-2 -mt-3 -mt-4 -translate-x-1/2 absolute align-items-center align-top backdrop-blur-sm bg-[#ec0607] bg-amber-100 bg-amber-50 bg-black/50 bg-blue-100 bg-blue-200 bg-blue-50 bg-blue-500 bg-blue-600 bg-blue-700 bg-emerald-100"></span>
  <span class="bg-emerald-200 bg-emerald-50 bg-emerald-500 bg-emerald-600 bg-gray-100 bg-gray-200 bg-gray-50 bg-gray-700 bg-gray-800 bg-gray-900 bg-green-100 bg-green-400 bg-green-50 bg-green-500 bg-green-600 bg-orange-50 bg-orange-500 bg-purple-100 bg-purple-200 bg-purple-50"></span>
  <span class="bg-red-100 bg-red-200 bg-red-50 bg-red-500 bg-red-600 bg-red-700 bg-rose-50 bg-slate-100 bg-slate-200 bg-slate-300 bg-slate-50 bg-slate-50/50 bg-teal-50 bg-transparent bg-white bg-yellow-100 bg-yellow-400 bg-yellow-500 bi bi-apple"></span>
  <span class="bi-cart3 bi-chevron-double-right bi-chevron-right bi-google-play bi-hourglass-split block border border-1 border-amber-200 border-b border-blue-100 border-blue-200 border-blue-300 border-blue-400 border-blue-500 border-emerald-200 border-gray-200 border-gray-300 border-gray-700 border-green-400"></span>
  <span class="border-l border-l-2 border-l-4 border-purple-200 border-r border-red-200 border-red-400 border-red-500 border-rose-400 border-slate-100 border-slate-200 border-slate-300 border-t border-transparent border-yellow-200 btn container cursor-not-allowed cursor-pointer d-flex"></span>
  <span class="dashboard-pie-chart disabled:bg-slate-100 disabled:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50 disabled:text-slate-500 divide-gray-200 divide-slate-100 divide-y dropdown-chevron duration-300 edit-balance-btn error eye-toggle fa-arrow-left fa-balance-scale fa-birthday-cake fa-book fa-briefcase fa-building"></span>
  <span class="fa-chart-bar fa-chart-line fa-check fa-check-circle fa-chevron-down fa-circle fa-clipboard-list fa-clock fa-cog fa-download fa-edit fa-envelope fa-eye fa-eye-slash fa-flag fa-globe fa-home fa-lock fa-minus-circle fa-pen"></span>
  <span class="fa-phone fa-plus fa-plus-circle fa-search fa-shield-alt fa-sign-out-alt fa-sitemap fa-sliders-h fa-stream fa-times fa-trash fa-trash-alt fa-umbrella-beach fa-undo fa-upload fa-user-plus fa-user-shield fa-users fas filter-pill"></span>
  <span class="fixed flash-message flex flex-1 flex-col flex-grow flex-shrink-0 flex-wrap focus:border-blue-500 focus:border-red-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-purple-500 focus:ring-red-500 font-bold font-extrabold font-light font-medium"></span>
  <span class="font-mono font-normal font-semibold gap-1 gap-2 gap-3 gap-4 gap-5 gap-6 gap-8 gap-x-2 gap-y-4 gap-y-5 gradient-background grid grid-cols-1 grid-cols-2 grid-cols-3 group group-hover:block"></span>
  <span class="h-10 h-12 h-16 h-2 h-2.5 h-20 h-3 h-4 h-5 h-56 h-6 h-72 h-8 h-[42px] h-[80vh] h-full h-screen hidden hover:bg-amber-100 hover:bg-amber-50"></span>
  <span class="hover:bg-blue-200 hover:bg-blue-50 hover:bg-blue-700 hover:bg-emerald-200 hover:bg-emerald-50 hover:bg-gray-100 hover:bg-gray-50 hover:bg-gray-700 hover:bg-gray-800 hover:bg-purple-200 hover:bg-red-200 hover:bg-red-50 hover:bg-red-600 hover:bg-red-700 hover:bg-slate-100 hover:bg-slate-200 hover:bg-slate-50 hover:border-blue-300 hover:border-blue-400 hover:opacity-95"></span>
  <span class="hover:shadow-md hover:text-blue-600 hover:text-blue-800 hover:text-emerald-800 hover:text-gray-200 hover:text-gray-700 hover:text-red-500 hover:text-red-800 hover:text-slate-600 hover:text-slate-700 hover:text-slate-800 hover:text-slate-900 hover:text-white hover:underline info inline inline-block inline-flex inset-0 inset-y-0"></span>
  <span class="italic items-center items-start justify-between justify-center justify-content-between justify-end justify-left leading-none leading-relaxed leading-tight left-0 left-1/2 lg:block lg:col-span-2 lg:flex lg:grid-cols-2 lg:grid-cols-3 lg:grid-cols-4 lg:hidden"></span>
  <span class="lg:px-8 lh-sm list-decimal list-disc list-group list-group-item list-inside max-h-60 max-w-2xl max-w-4xl max-w-5xl max-w-7xl max-w-md max-w-xs mb-0 mb-1 mb-2 mb-3 mb-4 mb-5"></span>
  <span class="mb-6 mb-8 md:block md:flex md:flex-row md:grid-cols-2 md:grid-cols-3 md:hidden md:items-center md:items-start md:justify-between md:mb-0 md:ml-6 md:mx-0 md:p-8 md:pl-12 md:place-items-start md:text-2xl md:w-fit min-h-100"></span>
  <span class="min-h-screen min-w-0 min-w-[180px] ml-10 ml-2 ml-3 ml-4 ml-7 ml-8 ml-auto mr-1 mr-2 mt-0.5 mt-1 mt-12 mt-2 mt-24 mt-3 mt-4 mt-6"></span>
  <span class="mt-8 mt-[-4px] mx-4 mx-5 mx-auto my-0 my-1 my-2 notosan notosans object-cover opacity-60 origin-top-right outline-none overflow-hidden overflow-x-auto overflow-y-auto p-0 p-1 p-12"></span>
  <span class="p-2 p-3 p-4 p-5 p-6 p-8 pb-16 pb-3 pl-3 pl-5 pl-8 place-items-center placeholder-slate-400 pointer-events-none pr-10 print:hidden progress-fill pt-1 pt-2 pt-4"></span>
  <span class="px-1.5 px-2 px-2.5 px-3 px-4 px-6 py-0.5 py-1 py-12 py-2 py-3 py-4 py-5 py-6 py-8 relative right-0 ring-3 ring-4 ring-blue-500"></span>
  <span class="ring-purple-500 ring-red-500 ring-white rounded rounded-4xl rounded-b-md rounded-full rounded-l-lg rounded-lg rounded-md rounded-r-lg rounded-xl shadow shadow-lg shadow-sm shadow-xl sidebar-dropdown-group sidebar-dropdown-menu sidebar-dropdown-toggle size-10"></span>
  <span class="size-2 size-6 sm:inline sm:max-w-md sm:mx-auto sm:px-6 sm:w-full space-x-3 space-x-4 space-y-1 space-y-2 space-y-3 space-y-4 space-y-5 space-y-6 space-y-8 sr-only sticky sticky-md-top success"></span>
  <span class="text-2xl text-3xl text-4xl text-[10px] text-amber-500 text-amber-600 text-amber-700 text-base text-black text-blue-500 text-blue-600 text-blue-700 text-blue-800 text-center text-emerald-500 text-emerald-600 text-emerald-700 text-emerald-800 text-end text-gray-200"></span>
  <span class="text-gray-300 text-gray-400 text-gray-500 text-gray-600 text-gray-700 text-gray-800 text-gray-900 text-green-500 text-green-600 text-green-700 text-green-800 text-left text-lg text-md text-muted text-orange-600 text-purple-600 text-purple-700 text-red-400 text-red-500"></span>
  <span class="text-red-600 text-red-700 text-red-800 text-right text-rose-600 text-rose-800 text-slate-400 text-slate-500 text-slate-600 text-slate-700 text-slate-800 text-slate-900 text-sm text-teal-600 text-white text-xl text-xs text-yellow-400 text-yellow-500 text-yellow-600"></span>
  <span class="text-yellow-700 toast-close toast-content top-0 top-1 top-4 tracking-wider transform transition transition-all transition-colors transition-opacity truncate uppercase w-0 w-10 w-12 w-16 w-3 w-4"></span>
  <span class="w-48 w-5 w-6 w-64 w-8 w-[200px] w-full w-px warning whitespace-nowrap xl:grid-cols-3 z-10 z-20 z-50"></span>

  <!-- Extra dynamic / conditional classes from Volt templates -->
  <span class="filter-pill bg-blue-100 text-blue-700 border-blue-200 hover:bg-blue-200"></span>
  <span class="filter-pill bg-emerald-100 text-emerald-700 border-emerald-200 hover:bg-emerald-200"></span>
  <span class="filter-pill bg-red-100 text-red-700 border-red-200 hover:bg-red-200"></span>
  <span class="filter-pill bg-purple-100 text-purple-700 border-purple-200 hover:bg-purple-200"></span>
  <span class="bg-purple-100 text-purple-700 border border-purple-200"></span>
  <span class="bg-emerald-100 text-emerald-700 border border-emerald-200"></span>
  <span class="bg-red-100 text-red-700 border border-red-200"></span>
  <span class="bg-slate-100 text-slate-600 border border-slate-200"></span>
  <span class="bg-blue-50 text-blue-700 border border-blue-200"></span>
  <span class="bg-slate-50/50"></span>
  <span class="bg-green-100 text-green-700"></span>
  <span class="bg-red-100 text-red-700"></span>
  <span class="progress-fill bg-red-500"></span>
  <span class="progress-fill bg-yellow-400"></span>
  <span class="progress-fill bg-emerald-500"></span>
  <span class="text-red-600"></span>
  <span class="text-emerald-600"></span>
  <span class="text-red-500"></span>
  <span class="text-yellow-400"></span>
  <span class="text-emerald-500"></span>
  <span class="open hidden fixed inset-y-0 left-0 z-40 lg:hidden"></span>
  <span class="divide-y divide-slate-100"></span>
</div>
